platform:
  - x64
configuration:
  - Release

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 23 x64
  - ps: npm config set cache %APPDATA%\npm-cache --global
  - ps: npm install --global pnpm
  - pnpm install

build_script:
  - pnpm run build:win

branches:
  only:
    - main
